language: java
jdk:
  - openjdk8
notifications:
  email: false
script: mvn install
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/LogBlock.jar"
  on:
    tags: true
